SpmlRequest:
    ns2_rrefix: ns2
    spml_prefix: spml
    spml_namespace: urn:siemens:names:prov:gw:SPML:2:0
    xsi_rrefix: xsi
    xsi_namespace: http://www.w3.org/2001/XMLSchema-instance
    default_subscriber_ns: urn:siemens:names:prov:gw:HSS_SUBSCRIBER:7:0
    subscriber_ns_tag: SUBSCRIBER_NS
    subscriber_version_tag: SUBSCRIBER_VERSION
    default_subscriber_version: HSS_SUBSCRIBER_v70
    
    object_class: Subscriber
    defalult_language: en_us
    public_identity_type: publicUserId/publicUserId
    private_identity_type: privateUserId/privateUserId
    new_generated: true
    
    return_resulting_object: none
    subscriber_type: subscriber:Subscriber
    subscriber_id_length: 32
    irs_suffix_length : 16
    delete_scope: all
    private_identity_search_name: impi
    public_identity_search_name: impu
    xsi_type: subscriber:HSSAliasType